In [4]:
numbers=[1,2,3,4,5,6,7,8,9,10]
for a in numbers:
    squared= a**2
    print(squared)

1
4
9
16
25
36
49
64
81
100


In [5]:
tup=(100,200,300,400)
tup.append(500)
print(tup)
#tuple cannot append it is immutable, whereas

AttributeError: 'tuple' object has no attribute 'append'

In [7]:
#By using concatination we can add
tup=(100,200,300,400)
tup1=tup + (500,)
print(tup1)

(100, 200, 300, 400, 500)


In [9]:
list=[1,2,3,1,2,3,4,5,] #converting list to set
set1=set(list)
print(set1)

{1, 2, 3, 4, 5}


In [14]:
dic={'Name':'John Doe', #creating a dictionary
'Age': 29,
'City':'New York'}
print (dic)

{'Name': 'John Doe', 'Age': 29, 'City': 'New York'}


In [22]:
a=2 #practice only using if else in same line
b=330
print ('A') if a>b else print ('B')


B


In [27]:
A=188 #using f-string more redable and concise when using multiple variables
if A % 2 == 0:
    print (f'The number {A} is even number')
else :
    print (f'The number {A} is odd number')
           


The number 188 is even number


In [38]:
tashi = lambda a : a ** 2 #using lambda function
print(tashi(12))



144


In [59]:
numbers=[1,2,3,4,5,6,7,8,9,10]
even_numbers =list(filter(lambda x: x % 2 == 0, numbers))
print(f'The even numbers are: {even_numbers}')

TypeError: 'list' object is not callable

In [60]:
import pandas as pd
df=pd.read_csv(r'/Users/binodrai/Desktop/Nume Doc/TAKEO/Python Basic Assignment/customer.csv')

In [31]:
df

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [49]:
df.head(5)


age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [50]:
df.tail(5)

age  gender review education purchased
45   61    Male   Poor        PG       Yes
46   64  Female   Poor        PG        No
47   38  Female   Good        PG       Yes
48   39  Female   Good        UG       Yes
49   25  Female   Good        UG        No

In [53]:
df.describe()

age
count  50.000000
mean   54.160000
std    25.658161
min    15.000000
25%    30.250000
50%    57.000000
75%    74.000000
max    98.000000

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [82]:
df = pd.DataFrame

In [83]:
age_column = df['age']
print(age_column)

TypeError: type 'DataFrame' is not subscriptable

In [84]:
df = pd.DataFrame

In [87]:
df_filtered = df[df['age'] > 30]
print(filtered_df)

TypeError: type 'DataFrame' is not subscriptable

In [89]:
import numpy as np
aid= np.arange(1, 11)
print("1D NumPy Array:")
print(aid)

1D NumPy Array:
[ 1  2  3  4  5  6  7  8  9 10]


In [92]:
aid_2d = np.random.randint(0, 10, size=(3, 4))
print("\n2D NumPy Array:")
print(aid_2d)


2D NumPy Array:
[[5 4 2 1]
 [8 0 2 2]
 [9 3 4 3]]


In [93]:
sliced_array = array_1d[2:5]
print("\nSliced Array:")
print(sliced_array)


Sliced Array:
[3 4 5]


In [94]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

In [95]:
result_array = array1 + array2
print("\nResult of Element-wise Addition:")
print(result_array)


Result of Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]


In [102]:
import panda as pd
colors['Red','Yellow', 'White',' Blue', 'Green']
color_series = pd.Series(colors)
print("Pandas Series:")
print(color_series)

ModuleNotFoundError: No module named 'panda'

In [103]:
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
    'Age': [25, 30, 35, 28, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Seattle']
}


In [105]:
df = pd.DataFrame(data_dict)
print("\nPandas DataFrame:")
print(df)


Pandas DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28      Houston
4    Emily   32      Seattle


In [106]:
df.head()

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28      Houston
4    Emily   32      Seattle

In [107]:
df.tail()

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28      Houston
4    Emily   32      Seattle

In [108]:
df.describe()

Age
count   5.000000
mean   30.000000
std     3.807887
min    25.000000
25%    28.000000
50%    30.000000
75%    32.000000
max    35.000000

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes


In [112]:
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age     City
2  Charlie   35  Chicago
4    Emily   32  Seattle


In [115]:
df = pd.DataFrame(data_dict)
salary_data = [60000, 70000, 80000, 55000, 75000]
df['Salary'] = salary_data
print(df)

      Name  Age         City  Salary
0    Alice   25     New York   60000
1      Bob   30  Los Angeles   70000
2  Charlie   35      Chicago   80000
3    David   28      Houston   55000
4    Emily   32      Seattle   75000


In [119]:
# 1. Create a list of 5 fruits and print the third fruit in the list.
fruits = ['Apple', 'Banana', 'Lichee', 'Orange', 'Mango']
print( fruits[2])

Lichee


In [132]:
fruits.extend(['Strawberry', 'Raspberry'])
print(fruits)

['Apple', 'Banana', 'Lichee', 'Orange', 'Mango', 'Fig', ['Fig', 'Grape'], 'Strawberry', 'Raspberry', 'Strawberry', 'Raspberry', 'Strawberry', 'Raspberry']


In [139]:
# 3. Remove the last element fom the list and print the list.
fruit1 = fruits.remove('Banana')
print(fruits)

['Lichee', 'Orange', 'Mango', 'Fig', ['Fig', 'Grape'], 'Strawberry', 'Raspberry', 'Strawberry', 'Raspberry', 'Strawberry', 'Raspberry']


In [141]:
last_fruit= fruits.pop()
print(fruits)

['Lichee', 'Orange', 'Mango', 'Fig', ['Fig', 'Grape'], 'Strawberry', 'Raspberry', 'Strawberry', 'Raspberry']


In [143]:
# 4. Check if 'Apple' is in the list and print the result as a boolean value.
print("'Apple' is in the list:", 'Apple' in fruits)

'Apple' is in the list: False


In [144]:
print('Fig' in fruits)



True


In [145]:
# 1. Create a tuple with 3 elements and print the second element.
my_tuple = ('Ant', 'Bat', 'Cat')
print(my_tuple[1])

Bat


In [146]:
# 2. Try to change an element in the tuple and observe the error.
# Tuples are immutable, so the following line will raise an error:
# my_tuple[0] = 'X'

In [147]:
# 3. Concatenate two tuples and print the result.
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
concatenated_tuple = tuple1 + tuple2
print(concatenated_tuple)

(1, 2, 3, 4, 5, 6)


In [148]:
# 1. Create two sets with some common elements and perform a union operation.
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5, 6}


In [149]:
# 2. Find the intersection of the two sets.
intersection_set = set1.intersection(set2)
print(intersection_set)

Intersection of set1 and set2: {3, 4}


In [151]:
# 3. Add a new element to a set and print the updated set.
set1.add(7)
print(set1)

{1, 2, 3, 4, 7}


In [152]:
# 1. Create a dictionary with 5 key-value pairs representing student names and their scores.
student_scores = {
    'Alice': 85,
    'Bob': 92,
    'Charlie': 78,
    'David': 88,
    'Emily': 90
}
print(student_scores)

{'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 88, 'Emily': 90}


In [153]:
# 2. Print all keys from the dictionary.
print(student_scores.keys())

dict_keys(['Alice', 'Bob', 'Charlie', 'David', 'Emily'])


In [154]:
# 3. Update the score of one student and print the updated dictionary.
student_scores['Bob'] = 95
print(student_scores)

{'Alice': 85, 'Bob': 95, 'Charlie': 78, 'David': 88, 'Emily': 90}


In [158]:
import numpy as np

# 1. Create a 1D Numpy array with 5 elements and print the array.
name = np.array([1, 2, 3, 4, 5])
print(name)

[1 2 3 4 5]


In [160]:
# 2. Perform element-wise multiplication of two Numpy arrays.
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = array1 * array2
print(result_array)

[ 4 10 18]


In [159]:
# 3. Calculate the mean of the Numpy array.
mean_value = np.mean(np_array)
print("Mean of the Numpy array:", mean_value)

Mean of the Numpy array: 3.0


In [161]:
import pandas as pd

# 1. Create a Pandas Series from a list of 5 cities and print the series.
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Seattle']
cities_series = pd.Series(cities)
print("Pandas Series of cities:")
print(cities_series)

Pandas Series of cities:
0       New York
1    Los Angeles
2        Chicago
3        Houston
4        Seattle
dtype: object


In [162]:
# 2. Create a Pandas DataFrame from a dictionary with columns 'Name', 'Age', and 'City' containing 3 rows of data.
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print("\nPandas DataFrame:")
print(df)


Pandas DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [167]:
# 3. Sort the DataFrame based on the 'Age' column.
df_sorted = df.sort_values(by='Age')
print(df_sorted)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [168]:
# 1. Write a lambda function to double a given number.
double = lambda x: x * 2
print(double(5))

10


In [165]:
# 2. Write a lambda function to check if a number is even or odd.
is_even = lambda x: x % 2 == 0
print("Is 7 even?", is_even(7))

Is 7 even? False


In [169]:
# 3. Use the lambda function to filter a list of numbers and print only the even numbers.
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)

TypeError: 'list' object is not callable